
version: '2'
services:
  web:
    image: gitea/gitea:1.15.3
    volumes:
      - ./data:/data
    ports:
      - "8929:3000"
      - "2022:22"
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=mskbogitea
    volumes:
      - ./db/:/var/lib/mysql

