registries:
  mskboRegistry:
    displayname: mskbo.keenetic.name:5505
    url: https://registry2-mskbo.mskbo.keenetic.name
    port: 5505 
    username: exampleUser
    password: examplePassword
    refresh-rate: "5m" # Example: 60s, 5m, 1h
    skip-tls-validation: true # REQUIRED for self signed certificates
    #dockerhub-integration: true # Optional - compares to dockerhub to determine if image up to date
